{
 "title": "Dashorad",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Life",
   "type": "gauge",
   "gridPos": { "h": 19, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "character_life", "legendFormat": "{{cid}}" }
   ]
  },
  {
   "title": "Life by team",
   "type": "gauge",
   "gridPos": { "h": 19, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(character_life, 0)) by (teamid)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Armor",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "character_armor", "legendFormat": "{{cid}}" }
   ]
  },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "character_speed", "legendFormat": "{{cid}}" }
   ]
  },
  {
   "title": "Strength",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 13, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "character_strength", "legendFormat": "{{cid}}" }
   ]
  }
 ]
}