global:
  scrape_interval: 5s  # Fréquence de collecte des métriques

scrape_configs:
  - job_name: 'flask_app'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:5000']  # Si Flask tourne localement sur le même hôte
